# Generated by Django 3.0.3 on 2020-02-20 22:02

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='comments',
            fields=[
                ('commentId', models.IntegerField(primary_key=True, serialize=False)),
                ('commentText', models.CharField(max_length=100)),
                ('commentTime', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='poststable',
            fields=[
                ('postId', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='replys',
            fields=[
                ('replyId', models.IntegerField(primary_key=True, serialize=False)),
                ('replyText', models.CharField(max_length=100)),
                ('replyTime', models.DateTimeField(default=datetime.datetime.now)),
                ('commentId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.comments')),
                ('postId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.poststable')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='likes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.poststable')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='comments',
            name='postId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.poststable'),
        ),
        migrations.AddField(
            model_name='comments',
            name='userId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
