# Generated by Django 3.0.3 on 2020-02-20 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='commentTime',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='replys',
            name='replyTime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
